// default package
// Generated 27 feb 2024, 17:34:23 by Hibernate Tools 6.3.1.Final

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Gatos generated by hbm2java
 */

@Entity
public class Gatos  implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer id;
     private String raza;
     private String nombre;
     private String foto;

    public Gatos() {
    }

    public Gatos(String raza, String nombre, String foto) {
       this.raza = raza;
       this.nombre = nombre;
       this.foto = foto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


