// default package
// Generated 27 feb 2024, 12:34:43 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Customerdemographics generated by hbm2java
 */
public class Customerdemographics implements java.io.Serializable {

	private String customerTypeId;
	private String customerDesc;
	private Set customerses = new HashSet(0);

	public Customerdemographics() {
	}

	public Customerdemographics(String customerTypeId, String customerDesc, Set customerses) {
		this.customerTypeId = customerTypeId;
		this.customerDesc = customerDesc;
		this.customerses = customerses;
	}

	public String getCustomerTypeId() {
		return this.customerTypeId;
	}

	public void setCustomerTypeId(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public String getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(String customerDesc) {
		this.customerDesc = customerDesc;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
